### ISSUE TITLE
Incompatible rxjs versions

### ISSUE THREAD

**Issue by jayphelps** [Netflix/ember-cli-nf-graph#19] opened 2015-04-07 03:48 UTC
```
Installing browser packages via Bower...
  cached git://github.com/mbostock/d3.git#3.5.5
  cached git://github.com/blesh/RxEmber.git#0.2.3
  cached git://github.com/Reactive-Extensions/RxJS.git#2.4.7
  cached git://github.com/Reactive-Extensions/RxJS.git#2.3.25
  new version for git://github.com/Reactive-Extensions/RxJS.git#~2.4.6
  resolved git://github.com/Reactive-Extensions/RxJS.git#2.4.10
  conflict Unable to find suitable version for rxjs
    1) rxjs ~2.3.22
    2) rxjs ~2.4.6
[?] Answer: 
```

Which is due to us saying [we need `~2.4.6`](https://github.com/Netflix/ember-cli-nf-graph/blob/f20f36967ebc3418d865565626b6c7bb832b2a41/blueprints/ember-cli-nf-graph/index.js#L9) but [RxEmber needs `~2.3.22`](https://github.com/blesh/RxEmber/blob/b5f66a4ce1249d385a4b2d0f7d5b0e3adb6f6a88/bower.json#L31)

**Comment by blesh** [comment] 2015-04-07 17:54
RxEmber needs to be updated, really. It was pinned to 2.3.22 a while ago because of a regression RxJS.

**Comment by blesh** [comment] 2015-04-07 23:09
This should all be fixed now in master and the next release.

**Closed by blesh** 2015-04-07 23:09 UTC
Labels: bug
